# Generated by Django 4.2.3 on 2023-07-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_white_username', models.CharField(max_length=100)),
                ('player_black_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_counter', models.IntegerField()),
                ('piece', models.CharField(max_length=20)),
                ('old_position', models.CharField(max_length=8)),
                ('new_position', models.CharField(max_length=8)),
                ('move', models.CharField(max_length=8)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChessApp.game')),
            ],
        ),
    ]
