# Generated by Django 4.2.3 on 2023-07-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='who_to_move',
            field=models.CharField(default='white', max_length=8),
        ),
    ]
